# Generated by Django 3.1.4 on 2020-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('netmiko', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintaxe', models.CharField(max_length=100)),
                ('modelos', models.ManyToManyField(to='network.Modelo')),
            ],
            options={
                'ordering': ['sintaxe'],
            },
        ),
    ]
