# Generated by Django 3.1.4 on 2020-12-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comando_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comando',
            name='modelos',
        ),
        migrations.AddField(
            model_name='modelo',
            name='comandos',
            field=models.ManyToManyField(to='network.Comando'),
        ),
    ]
