# Generated by Django 3.1.4 on 2020-12-08 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201207_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='name',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='network.modelo'),
        ),
    ]
