# Generated by Django 3.1.4 on 2020-12-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_comando_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comando',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
